services:
  - type: web
    name: csr-proposal-checker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-MiniLM-L6-v2')"  # Pre-download AI model
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.7"