services:
  - type: web
    name: csr-proposal-checker
    runtime: python
    pythonVersion: "3.9.7"  # Recommended stable version
    
    # Build commands
    buildCommand: |
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-MiniLM-L6-v2')"  # Pre-download AI model
      
    # Startup command (matches your run.py)
    startCommand: "gunicorn run:app"
    
    # Environment settings
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.7"
      - key: GREENLET_FORCE_CORE  # Required for Python 3.11+
        value: "1"
