services:
  - type: web
    name: csr-proposal-checker
    runtime: python
    pythonVersion: "3.9.7"  # Most stable with all dependencies
    
    # Build commands
    buildCommand: |
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-MiniLM-L6-v2')"  # Pre-download model
      
    # Startup
    startCommand: "gunicorn run:app"
    
    # Environment variables
    envVars:
      - key: UPLOAD_FOLDER
        value: "/var/data/uploads"  # Persistent storage on Render
      - key: PYTHON_VERSION
        value: "3.9.7"
      - key: GREENLET_FORCE_CORE
        value: "1"  # Required for Python 3.11+ compatibility
      - key: FLASK_APP
        value: "run.py"  # Explicitly point to entry file

    # Advanced
    plan: free  # For starter projects
    autoDeploy: true  # Enable automatic deploys
