services:
  - type: web
    name: csr-proposal-checker
    runtime: python
    pythonVersion: "3.9.7"
    buildCommand: |
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-MiniLM-L6-v2')"
    startCommand: "gunicorn run:app"
